# Generated by Django 5.0.3 on 2024-04-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="roomuuid",
            field=models.IntegerField(unique=True),
        ),
    ]
