# Generated by Django 5.0.3 on 2024-04-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_room_roomuuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="cid",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="url",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
